### ISSUE TITLE
Villager breeding doesn't work

### ISSUE THREAD

**Issue by enderprism** [gliscowo/interactic#10]
When using this mod on the client as well as the server, the villager breeding stops working because the villagers seem to struggle while trying to pick up food.

I have no logs.

Minecraft version is 1.18.2 Fabric.

**Comment by Noaaan** [comment]
Do you have `mobGriefing` disabled? Minecraft does not let villagers pick up food if its disabled.

**Comment by enderprism** [comment]
Thanks for the answer! It was exactly this.
