### ISSUE TITLE
Block Items Land At Odd Angles

### ISSUE THREAD

**Issue by ghost** [gliscowo/interactic#11]
`MC 1.18.2`
`Interactic 0.1.10`

![image](https://user-images.githubusercontent.com/24266948/180929541-fd0fa483-9a15-49a8-9112-183183d71904.png)

Not sure why it doesn't sit flat when other "flat" items rest fine on the ground.

**Comment by xR4YM0ND** [comment]
oh yeah , it would be neat if they land flat

**Comment by gliscowo** [comment]
Blocks landing at a random angle is very much an intended stylistic decision, simply having them lay flat does for one not make much sense with many block shapes and looks plain boring. However, if a config option for this is desired, I'll see about adding it as soon as I get the time
Cheers

**Comment by xR4YM0ND** [comment]
I would love to test this feature, i think styled looks great too , but configurable would be awesome

**Comment by ghost** [comment]
Definitely desired, I understand how it is stylistic but reconfigurability would be perfect.
