### ISSUE TITLE
[Suggestion] Visual Despawn Indicator

### ISSUE THREAD

**Issue by ghost** [gliscowo/interactic#12]
Some options:
- Item flashing or a gradual fade in opacity when within a configurable duration of despawning (similar to [Clear Despawn](https://www.curseforge.com/minecraft/mc-mods/clear-despawn-fabric))
- Some sort of small, clean "lifespan" progress bar that is visible when you look at the item

**Comment by gliscowo** [comment]
I don't quite see the value in implementing this personally, given that Clear Despawn already does it perfectly well. If anything, it might be worthwhile suggesting the progress bar idea to them.
Cheers

**Comment by ghost** [comment]
Figured I'd suggest it here as avoiding an extra mod is always nice and it seemed to fit. Fair enough though, will raise an issue with them at some point!
