### ISSUE TITLE
Crash between interactic and lava java

### ISSUE THREAD

**Issue by GitPois1x** [gliscowo/interactic#13]
Game crashes when modded item from lava java is thrown on the ground
https://www.curseforge.com/minecraft/mc-mods/lava-java
[crash-2022-12-03_20.19.01-client.txt](https://github.com/gliscowo/interactic/files/10147649/crash-2022-12-03_20.19.01-client.txt)

**Comment by Noaaan** [comment]
This would have to be fixed on Lava Java's side. The `world` is annotated with `@Nullable`, yet it is never checked whether or not it is null, and as such it can crash whenever they try to check for the worlds time for their tooltip handling. 
https://github.com/Tigereye504/lava-java/blob/master/src/main/java/net/tigereye/lavajava/item/LavaJavaItem.java#L110

**Comment by gliscowo** [comment]
This has since been fixed in the [1.19.4 release](https://modrinth.com/mod/interactic/version/0.2.0+1.19.4)
Cheers
