### ISSUE TITLE
Item Filter (Client Side only)

### ISSUE THREAD

**Issue by KhaozFrost** [gliscowo/interactic#16]
I was wondering if its possible to have this clientside only and use a hotkey to open the menu rather then needing the mod on both the server and the client. (I'd rather not introduce a hard mod that players need to have to be able to join)

**Comment by gliscowo** [comment]
While I do understand that this would be useful, it's not really feasibly to implement as client-side functionality, as the server fundamentally decides when Item entities get picked up - the client has no say over this.

As such, I'll be closing this issue as wontfix

Cheers
