### ISSUE TITLE
ItemEntities with .setNeverPickUp() can be picked up.

### ISSUE THREAD

**Issue by Micaxs** [gliscowo/interactic#20]
Hello,

I noticed there is a issue where when a mod adds an itementity to the world and set this item with `.setNerverPickUp()`, the item can still be picked up with this mod when the config `rightClickPickup": true` is set.

This shouldn't be the case as it breaks several mods where an item is being diplayed but shouldn't be allowed to be picked up or interacted with.

**Comment by gliscowo** [comment]
Thanks for reporting this, a fix has now been released in [0.2.2](https://modrinth.com/mod/interactic/version/0.2.2+1.20.3)
Cheers
