### ISSUE TITLE
mod mismatch

### ISSUE THREAD

**Issue by shadins** [gliscowo/interactic#23]
I have a small server that uses this mod, I haven't done any updating of client or server files and trying to log into the server today I am getting an error stating that this mod is showing a mismatch between server and client, I have removed the mod and the lib and re-added them and still had the issue, at the moment I can only get on the server by removing this mod from the server side and lose out on server features of the mod for the time being.
![image](https://github.com/gliscowo/interactic/assets/33010981/63acd462-264f-4101-97de-a6d4e1efccae)

**Comment by Noaaan** [comment]
If you wish to use Interactic on a server which does not have it you need to enable "Client Only Mode" in the config

**Comment by shadins** [comment]
@Noaaan I have the mod and lib running on both client and server and am getting this mismatch error

**Comment by Noaaan** [comment]
I still think in this case you have a mismatched config option. Have you disabled the Item Filter on either the server or client, but not the other? That would cause this issue, and it should throw this error in the logs

**Comment by shadins** [comment]
@Noaaan I can check to see in a few mins, however it was working normally less than 12 hrs ago I was logged into the server and all the features were working as intended.

**Comment by shadins** [comment]
@Noaaan 
Well, I found that the config on the server was broken. It was filled with text I couldn't read. I deleted it and rebooted the server to rebuild the config file and it seems to work now
