### ISSUE TITLE
Any Plan to port to forge on 1.19.2?

### ISSUE THREAD

**Issue by QianFuv** [gliscowo/interactic#25]
This mod is the most powerful and best mod I have found after searching for three days. I would be extremely grateful if it could be ported to Forge!

**Comment by gliscowo** [comment]
On Forge, I recommend you use [ItemPhysic](https://modrinth.com/mod/itemphysic), which inspired the primary features of Interactic. This mod however, will not be ported to Forge (or at least not by me - if you find someone else to do it, they're free to go ahead)

Cheers
