### ISSUE TITLE
Compatibility with LambDynamicLights

### ISSUE THREAD

**Issue by GogiBoy102** [gliscowo/interactic#26]
Dropped items like torches dont light up the ground below when used with interactic

**Comment by Fyoncle** [comment]
Compat when..

**Comment by solonovamax** [comment]
What do you mean?

I just tested it with LambDynamicLights, interactic, and sodium (all on latest version), and the dynamic lighting works perfectly fine with the fancy item rendering

![2024-06-15_20 08 29](https://github.com/gliscowo/interactic/assets/46940694/65ea3bf3-ded7-463f-b632-03684098c146)

**Comment by Fyoncle** [comment]
> What do you mean?
> 
> I just tested it with LambDynamicLights, interactic & sodium, and the dynamic lighting works perfectly fine
> 
> ![2024-06-15_20 08 29](https://private-user-images.githubusercontent.com/46940694/340051443-65ea3bf3-ded7-463f-b632-03684098c146.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0OTY4NjQsIm5iZiI6MTcxODQ5NjU2NCwicGF0aCI6Ii80Njk0MDY5NC8zNDAwNTE0NDMtNjVlYTNiZjMtZGVkNy00NjNmLWI2MzItMDM2ODQwOThjMTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDAwMDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhM2Q2NmM0MjUzZjMxNjY0YTkyMjg1MWFkZjQ1MDRhNTU1N2YzYzlmMGE2N2U0MmJmZjRlY2M1OWIzMmI3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EKW8YALL-jMMUJSuyvu7Sufsg7HKJB-ks_MgkBDpMMs)

Uhhh, then why this issue exist

**Comment by solonovamax** [comment]
> Uhhh, then why this issue exist

that's why I'm asking

I even set up a whole dev env on my laptop to look into fixing this lol

**Comment by Fyoncle** [comment]
> > Uhhh, then why this issue exist
> 
> that's why I'm asking
> 
> I even set up a whole dev env on my laptop to look into fixing this lol

Oh lmao, thanks for your efforts and bringing this to sun light i guess, but the dev doesn't seem to be gonna close this issue ever LOL

**Comment by GogiBoy102** [comment]
I made this issue a year ago, i dont even properly exactly what it was

**Comment by GogiBoy102** [comment]
i dont think theres any thing to add here now unless i run into this issue again

**Comment by GogiBoy102** [comment]
sorry to everyone
