### ISSUE TITLE
Shift + left-click makes items disappear in the Item Filter

### ISSUE THREAD

**Issue by Lemonzyy** [gliscowo/interactic#27]
# Mod list
- Interactic [0.2.0+1.20]
- Fabric API [0.91.0+1.20.1]
- oωo [0.11.2+1.20]

# Video
https://youtu.be/u_HICJd52CQ

**Comment by gliscowo** [comment]
Thanks for reporting this, a fix has now been released in [0.2.2](https://modrinth.com/mod/interactic/version/0.2.2+1.20.3)
Cheers
