### ISSUE TITLE
1.18.2 Crash

### ISSUE THREAD

**Issue by halflingisband** [gliscowo/interactic#7]
I disabled the setting for the item sorter and fabric will no longer launch with Interactic added. Since I can no longer run Ineteractic, I can't re-enable the sorter.

**Comment by gliscowo** [comment]
Could you give us the crash report, or ideally the entire `latest.log` file from right after the crash? With as little information as you have given here, it is basically impossible for us figure out what's wrong
Cheers

**Comment by legosteenjaap** [comment]
I believe i have the same issue, my game also crashes when i disable the item filter. Here is my log: https://paste.ee/p/zw72i

**Comment by gliscowo** [comment]
Fixed in 0.1.10
