### ISSUE TITLE
Changes in Config File "interactic.json5" causing crashes

### ISSUE THREAD

**Issue by smokedzn** [gliscowo/interactic#8]
Active mods:
interactic-0.1.9+1.18 
cloth-config-6.2.57-fabric
fabric-api-0.47.10+1.18.2

Optional active mods used:
notenoughcrashes-4.1.4+1.18.1-fabric

Problem occurs when changing options over Mod Menu or manually over the "interactic.json5" config file.
> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 07/03/2022, 12:35
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'confabricate'!
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
> 	at net.minecraft.class_310.redirect$bmf000$catchFabricInit(class_310.java:12453)
> 	at net.minecraft.class_310.<init>(class_310.java:452)
> 	at net.minecraft.client.main.Main.main(Main.java:197)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3486 failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at ca.stellardrift.confabricate.mixin.FluidTagsAccessor.getRequiredTags(FluidTagsAccessor.java)
> 	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.populate(MinecraftSerializers.java:245)
> 	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.collection(MinecraftSerializers.java:192)
> 	at ca.stellardrift.confabricate.Confabricate.onInitialize(Confabricate.java:97)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> 	... 17 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
> 	... 25 more
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [confabricate.accessor.mixins.json:FluidTagsAccessor] from phase [DEFAULT] in config [confabricate.accessor.mixins.json] from mod [confabricate] FAILED during APPLY
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
> 	... 28 more
> Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_23680:Lnet/minecraft/class_5120; in net/minecraft/class_3486 for confabricate.accessor.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getRequiredTags()Lnet/minecraft/class_5120; [INJECT Applicator Phase -> confabricate.accessor.mixins.json:FluidTagsAccessor -> Apply Accessors ->  -> Locate -> confabricate.accessor.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getRequiredTags()Lnet/minecraft/class_5120;]
> 	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
> 	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
> 	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
> 	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
> 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
> 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
> 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> 	at ca.stellardrift.confabricate.mixin.FluidTagsAccessor.getRequiredTags(FluidTagsAccessor.java)
> 	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.populate(MinecraftSerializers.java:245)
> 	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.collection(MinecraftSerializers.java:192)
> 	at ca.stellardrift.confabricate.Confabricate.onInitialize(Confabricate.java:97)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
> 	at net.minecraft.client.MinecraftClient.redirect$bmf000$catchFabricInit(MinecraftClient:12453)
> 	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452)
> 	at net.minecraft.client.main.Main.main(Main:197)
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.lang.reflect.Method.invoke(Method.java:577)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.lang.reflect.Method.invoke(Method.java:577)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at fudge.notenoughcrashes.mixinhandlers.EntryPointCatcher.handleEntryPointError(EntryPointCatcher.java:28)
> 	at net.minecraft.class_310.redirect$bmf000$catchFabricInit(class_310.java:12455)
> 	at net.minecraft.class_310.<init>(class_310.java:452)
> 	at net.minecraft.client.main.Main.main(Main.java:197)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by gliscowo** [comment]
I can't be entirely certain, but this does not look like an Interactic issue to me. As the crash report clearly states, the problem is being caused by Confabricate, which is most definitely being loaded additionally to the mods you listed. From the kind of crash this is, I would assume you're trying to run a 1.18.1 build of Confabricate on 1.18.2. I would recommend inspecting your mod list once more and sending the entire log in here if you're not able to solve it
Cheers
