### ISSUE TITLE
Disabling auto pickup interferes with Fabrication's instant pickup

### ISSUE THREAD

**Issue by copygirl** [gliscowo/interactic#9]
### Versions

- Minecraft `1.18.2`
- Fabric Loader `0.14.4`
- Interactic `0.1.10+1.18`
- Fabrication `2.3.1-exp3` (from [GitHub releases](https://github.com/unascribed/Fabrication/releases/tag/v2.3.0))

### To Reproduce

- Set `autoPickup` in Interactic to `false`
- Set `weird_tweaks.instant_pickup` in Fabrication to `true`
- Attempt to break a block in the game
- The block doesn't get picked up unless sneaking

### Description

In Fabrication there is a feature called `Instant Pickup` that will automatically transfer items to a player's inventory when a block is broken or an entity is killed with a melee weapon. It achieves this by [setting their pickup delay to 0 and calling `onPlayerCollision`](https://github.com/unascribed/Fabrication/blob/d04acd7d116318861b22d5da0e1a4e229291360f/src/main/java/com/unascribed/fabrication/logic/InstantPickup.java), presumably to achieve best possible mod support. However, Interactic [injects itself into exactly that method](https://github.com/gliscowo/interactic/blob/1.18.2/src/main/java/interactic/mixin/ItemEntityMixin.java#L70), effectively making Fabrication's tweak moot.

This is a very specific interactions between two mods and this particular choice of settings might be unique to what I'm trying to do, but I nonetheless wanted to create an issue. I'm not sure what the solution here could be, but perhaps there is something you can do about it.

In case there is any confusion as to my choice of settings: I like having Fabrication's instant pickup enabled, as I tend to want the blocks I'm mining. This way, I don't lose anything when I'm mining downwards, or have to look after I've done some digging. The pickup delay is also just long enough to be annoying at times. At the same time however, I'm not a huge fan of picking up random stuff that was littered about, or intentionally thrown out to let despawn, so Interactic helps with that.

Thanks for your time, and the nice mod! :green_heart:

**Comment by gliscowo** [comment]
Hey, thanks for reporting this issue. It has now been resolved by unascribed/Fabrication#460 and should soon be available in a release
Have a great day

**Comment by copygirl** [comment]
Thank you very much for looking into this so quickly.
